### ISSUE TITLE
Incorrect location URLs

### ISSUE THREAD

**Issue by GetTheData** [gladstonemrm/SportsAndLeisureManagement#2]
All the location URLs I am checking are failing.

I have extracted a list of all locations and their data here:

https://www.getthedata.com/openactive/everyone-active/locations

If you click any of the location URLs you get a 404.

By way of an example, the URL for Ryedale Swim and Fitness Centre in the feed is:

https://www.everyoneactive.com/centres/Ryedale-Swim-&-Fitness-Centre

The correct URL is:

https://www.everyoneactive.com/centre/ryedale-swim-and-fitness-centre/

**Comment by DebbieGiordano1** [comment]
issue resolved
