### ISSUE TITLE
Some sessions might be erroneously categorised as "Group Exercise 14+ Yrs"

### ISSUE THREAD

**Issue by nishaldesai** [gladstonemrm/SportsAndLeisureManagement#4]
Hi team Everyone Active! :)

We're just analysing your data feed for use within Public Health England's Change4Life activity finder this summer. 

I've noticed quite a few sessions have the category "Group Exercise 14+ Yrs" but not all of the sessions might be open to people younger than 16 or 18.

For example, the session "Group Cycling Express" at Sunbury Leisure Centre says "Open to: Adults Only" on the timetable on the [Everyone Active website](https://www.everyoneactive.com/centre/sunbury-leisure-centre/) - see attached, whereas in the open data feed I can see this session with activity categories of: "Group Exercise 14+ Yrs,Group Exercise Classes,Calorie Killers".

This is one example I've pulled out, happy to see if there's more if that would be useful to help you diagnose the issue.

Please clarify if the website is wrong, or the open data feed is wrong (or something else)? This will help us work out whether we should be displaying these types of classes to Change4Life users.

Thanks!

<img width="1257" alt="screen shot 2018-07-19 at 18 35 21" src="https://user-images.githubusercontent.com/26442708/42960116-cddbfa04-8b82-11e8-9316-0a353c4a5de6.png">

**Comment by DebbieGiordano1** [comment]
this is a question about our website but I don’t think its relevant to the feed as I would have though you use MinAge / MaxAge instead of a our ActivityGroups and how they are categorised on the website?
Nick confirmed that MinAge MaxAge is used
