### ISSUE TITLE
Dataset site down

### ISSUE THREAD

**Issue by chrisbancroft** [gladstonemrm/SportsAndLeisureManagement#8]
https://data.everyoneactive.com/OpenActive is down and displaying 522 error. 

![image](https://user-images.githubusercontent.com/114655014/217811962-fb5310a1-7d15-46f8-ae5c-fcfdbdb612a3.png)

**Comment by chrisbancroft** [comment]
Hi @DebbieGiordano1, hope you are well. we have come across this issue and were wondering if you have any ideas as to why this has occurred? Thanks. Chris

**Comment by DebbieGiordano1** [comment]
Hi,

Please could you try this again and confirm if its working.

Regards,

Debbie Giordano | Applications Manager
Everyone Support Hub

**Comment by chrisbancroft** [comment]
Thanks for the speedy reply @DebbieGiordano1  and I can confirm that the link is now working so thank you for fixing the issue as quickly as you did.
Kind regards
Chris

**Comment by chrisbancroft** [comment]
afternoon @DebbieGiordano1 apologies for messaging again but it appears after the fix was implemented yesterday, 3 feeds are now coming through. we have data.everyoneactive.com/openactive,  tst.myeveryoneactive.com/openative and uatbook.myeveryoneactive.com/openactive. i would be grateful if you could review and if the tst and uat feeds aren't needed, could you please arrange for them to be switched off. thanks in advance. chris

**Comment by DebbieGiordano1** [comment]
Hi Chris,

These would have been running before the issue, they are continuously running for development purposes.

Thanks.

Regards,

Debbie Giordano | Applications Manager
Everyone Support Hub
